export const IDS = {
  navBrand: "nav-brand",
  navLink: (k) => `nav-link-${k}`,
  navResumeBtn: "nav-resume-btn",
  heroPrimaryCta: "hero-primary-cta",
  heroSecondaryCta: "hero-secondary-cta",
  heroAvailabilityBadge: "hero-availability-badge",
  heroGithub: "hero-social-github",
  heroLinkedin: "hero-social-linkedin",
  heroTryhackme: "hero-social-tryhackme",
  heroRoleRotator: "hero-role-rotator",
  techTicker: "tech-ticker",
  projectCard: (slug) => `project-card-${slug}`,
  projectViewDetails: (slug) => `project-view-details-${slug}`,
  projectGithub: (slug) => `project-github-${slug}`,
  projectsFilter: (k) => `projects-filter-${k}`,
  globeCanvas: "globe-canvas",
  terminalInput: "terminal-input",
  terminalOutput: "terminal-output",
  terminalClear: "terminal-clear",
  githubRepoCard: (name) => `github-repo-${name}`,
  contactName: "contact-name",
  contactEmail: "contact-email",
  contactSubject: "contact-subject",
  contactMessage: "contact-message",
  contactSubmit: "contact-submit",
  backToTop: "back-to-top",
  scrollProgress: "scroll-progress",
};
